{
 "title": "Ethereum Nodes",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "single_dev",
    "label": "Single device nodes",
    "query": "SHOW TAG VALUES FROM \"status_node\" with Key= \"host\" "
   },
   {
    "name": "dual_dev",
    "label": "Dual device nodes",
    "query": "SHOW TAG VALUES FROM \"status_node\" with Key= \"host\" "
   },
   { "name": "dual_exec", "query": "${dual_dev}_exec" },
   { "name": "dual_consensus", "query": "${dual_dev}_consensus" }
  ]
 },
 "panels": [
  {
   "title": "All Nodes Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rpi5a node status",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "status_node",
       "select": [
        [
         { "params": [ "active_percent" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=", "value": "rpi5a_s" }
       ]
      }
     ]
    },
    {
     "title": "Rpi5b node status",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "status_node",
       "select": [
        [
         { "params": [ "active_percent" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=", "value": "rpi5b_s" }
       ]
      }
     ]
    },
    {
     "title": "Rpi5c node status",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "status_node",
       "select": [
        [
         { "params": [ "active_percent" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=", "value": "rpi5c_s" }
       ]
      }
     ]
    },
    {
     "title": "Rpi5d node status",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "status_node",
       "select": [
        [
         { "params": [ "active_percent" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=", "value": "rpi5d_s" }
       ]
      }
     ]
    },
    {
     "title": "Dual0 node status",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "status_node",
       "select": [
        [
         { "params": [ "active_percent" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=", "value": "dual0_d" }
       ]
      }
     ]
    },
    {
     "title": "Dual1 node status",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "status_node",
       "select": [
        [
         { "params": [ "active_percent" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=", "value": "dual1_d" }
       ]
      }
     ]
    },
    {
     "title": "Sync status history",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "measurement": "status_node",
       "query": "SELECT mean(\"used_percent\") FROM \"cpu\" WHERE (\"host\"::tag = 'ethtest1.local') AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "active_percent" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=", "value": "rpi5a_s" }
       ]
      }
     ]
    },
    {
     "title": "Sync status history",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "measurement": "status_node",
       "query": "SELECT mean(\"used_percent\") FROM \"cpu\" WHERE (\"host\"::tag = 'ethtest1.local') AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "active_percent" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=", "value": "rpi5b_s" }
       ]
      }
     ]
    },
    {
     "title": "Sync status history",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "measurement": "status_node",
       "query": "SELECT mean(\"used_percent\") FROM \"cpu\" WHERE (\"host\"::tag = 'ethtest1.local') AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "active_percent" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=", "value": "rpi5c_s" }
       ]
      }
     ]
    },
    {
     "title": "Sync status history",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "measurement": "status_node",
       "query": "SELECT mean(\"used_percent\") FROM \"cpu\" WHERE (\"host\"::tag = 'ethtest1.local') AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "active_percent" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=", "value": "rpi5d_s" }
       ]
      }
     ]
    },
    {
     "title": "Sync status history",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "measurement": "status_node",
       "query": "SELECT mean(\"used_percent\") FROM \"cpu\" WHERE (\"host\"::tag = 'ethtest1.local') AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "active_percent" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=", "value": "dual0_d" }
       ]
      }
     ]
    },
    {
     "title": "Sync status history",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "measurement": "status_node",
       "query": "SELECT mean(\"used_percent\") FROM \"cpu\" WHERE (\"host\"::tag = 'ethtest1.local') AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "active_percent" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=", "value": "dual1_d" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Dual Device Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node status",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "status_node",
       "select": [
        [
         { "params": [ "active_percent" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$dual_dev$/" }
       ]
      }
     ]
    },
    {
     "title": "Exec dev CPU load",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 4, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$dual_exec$/" }
       ]
      }
     ]
    },
    {
     "title": "Execution device CPU load history",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 17, "x": 7, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "cpu",
       "query": "SELECT mean(\"used_percent\") FROM \"cpu\" WHERE (\"host\"::tag = 'ethtest1.local') AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$dual_exec$/" }
       ]
      }
     ]
    },
    {
     "title": "Execution",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "status_exec",
       "select": [
        [
         { "params": [ "active_percent" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$dual_dev$/" }
       ]
      }
     ]
    },
    {
     "title": "Consensus",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "status_consensus",
       "select": [
        [
         { "params": [ "active_percent" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$dual_dev$/" }
       ]
      }
     ]
    },
    {
     "title": "Sync progress",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "chain",
       "select": [
        [
         { "params": [ "sync_part_perc_0" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$dual_dev$/" }
       ]
      },
      {
       "measurement": "chain",
       "select": [
        [
         { "params": [ "sync_part_perc_1" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$dual_dev$/" }
       ]
      },
      {
       "measurement": "chain",
       "select": [
        [
         { "params": [ "sync_part_perc_2" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$dual_dev$/" }
       ]
      },
      {
       "measurement": "chain",
       "select": [
        [
         { "params": [ "sync_part_perc_3" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$dual_dev$/" }
       ]
      }
     ]
    },
    {
     "title": "Execution device memory use",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 4, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mem",
       "query": "SELECT mean(\"used_bytes\") FROM \"mem\" WHERE (\"host\"::tag = 'ethtest1.local') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "used_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$dual_exec$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "swap",
       "select": [
        [
         { "params": [ "used_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$dual_exec$/" }
       ]
      }
     ]
    },
    {
     "title": "Execution device disk use",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "select": [
        [
         { "params": [ "used_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$dual_exec$/" }
       ]
      }
     ]
    },
    {
     "title": "Sync status history",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "measurement": "status_node",
       "query": "SELECT mean(\"used_percent\") FROM \"cpu\" WHERE (\"host\"::tag = 'ethtest1.local') AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "active_percent" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$dual_dev$/" }
       ]
      }
     ]
    },
    {
     "title": "Cons dev CPU load",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 4, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$dual_consensus$/" }
       ]
      }
     ]
    },
    {
     "title": "Consensus device CPU load history",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 17, "x": 7, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "cpu",
       "query": "SELECT mean(\"used_percent\") FROM \"cpu\" WHERE (\"host\"::tag = 'ethtest1.local') AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$dual_consensus$/" }
       ]
      }
     ]
    },
    {
     "title": "Latest block",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "chain",
       "select": [
        [
         { "params": [ "last_block" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$dual_dev$/" }
       ]
      }
     ]
    },
    {
     "title": "Chain head",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "chain",
       "select": [
        [
         { "params": [ "last_block" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$dual_dev$/" }
       ]
      }
     ]
    },
    {
     "title": "Consensus device memory use",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 4, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mem",
       "query": "SELECT mean(\"used_bytes\") FROM \"mem\" WHERE (\"host\"::tag = 'ethtest1.local') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "used_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$dual_consensus$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "swap",
       "select": [
        [
         { "params": [ "used_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$dual_consensus$/" }
       ]
      }
     ]
    },
    {
     "title": "Consensus device disk use",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "select": [
        [
         { "params": [ "used_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$dual_consensus$/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Single Device Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Node status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "status_node",
     "query": "SELECT \"active_percent\" FROM \"status_node\" WHERE (\"host\"::tag =~ /^$|dev4$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "active_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$single_dev$/" }
     ]
    }
   ]
  },
  {
   "title": "Chain Head",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "chain",
     "select": [
      [
       { "params": [ "last_block" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$single_dev$/" }
     ]
    }
   ]
  },
  {
   "title": "Chain head",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "chain",
     "select": [
      [
       { "params": [ "last_block" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$single_dev$/" }
     ]
    }
   ]
  },
  {
   "title": "Execution",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "status_exec",
     "select": [
      [
       { "params": [ "active_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$single_dev$/" }
     ]
    }
   ]
  },
  {
   "title": "Consensus",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "status_consensus",
     "select": [
      [
       { "params": [ "active_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$single_dev$/" }
     ]
    }
   ]
  },
  {
   "title": "Sync progress",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "chain",
     "select": [
      [
       { "params": [ "sync_part_perc_0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$single_dev$/" }
     ]
    },
    {
     "measurement": "chain",
     "select": [
      [
       { "params": [ "sync_part_perc_1" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$single_dev$/" }
     ]
    },
    {
     "measurement": "chain",
     "select": [
      [
       { "params": [ "sync_part_perc_2" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$single_dev$/" }
     ]
    },
    {
     "measurement": "chain",
     "select": [
      [
       { "params": [ "sync_part_perc_3" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$single_dev$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"used_percent\") FROM \"cpu\" WHERE (\"host\"::tag =~ /^$dev5$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$single_dev$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU load history",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"used_percent\") FROM \"cpu\" WHERE (\"host\"::tag = 'ethtest1.local') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$single_dev$/" }
     ]
    }
   ]
  },
  {
   "title": "Sync status history",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "measurement": "status_node",
     "query": "SELECT mean(\"used_percent\") FROM \"cpu\" WHERE (\"host\"::tag = 'ethtest1.local') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "active_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$single_dev$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"used_bytes\") FROM \"mem\" WHERE (\"host\"::tag = 'ethtest1.local') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "used_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$single_dev$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "used_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$single_dev$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$single_dev$/" }
     ]
    }
   ]
  }
 ]
}